RESORTS

[{"address": "100 Dercum Square", "city": "Keystone", "state": "CO", "zipcode": 80435, "name": "Keystone Resort", "photo_url": "https://dam-assets.vailresorts.com/is/image/vailresorts/20180123_KY_balluff_001:Product-Cards-Landing?resMode=sharp2&w=1002&h=668&wid=382&fit=constrain,1&dpr=on,2.625", "average_rating": 0, "elevation": 12408, "price": 4, "vertical_drop": 3128, "num_trails": 130, "pass_type": "Epic", "resort_website": "https://www.keystoneresort.com/"},
{"address": "1599 Ski Hill Rd", "city": "Breckenridge", "state": "CO", "zipcode": 80424, "name": "Breckenridge Ski Resort", "photo_url": "https://dam-assets.vailresorts.com/is/image/vailresorts/Breckenridge-Mountain-Info-Heros-2?wid=1400&fit=vfit,1&resMode=sharp2&w=1400&h=400&hei=1050&dpr=on,2.625", "average_rating": 0, "elevation": 12998, "price": 4, "vertical_drop": 3398, "num_trails": 187, "pass_type": "Epic", "resort_website": "https://www.breckenridge.com/"},
{"address": "183 E Gore Creek Dr", "city": "Vail", "state": "CO", "zipcode": 81657, "name": "Vail Ski Resort", "photo_url": "https://www.travelandleisure.com/thmb/YFdvTj2kKw5qIWLMVhSbFhcs6qA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/skiing-vail-mountain-colorado-MMVAIL1221-1543ad9d836f403989991d357e2467de.jpg", "average_rating": 0, "elevation": 11570, "price": 5, "vertical_drop": 3450, "num_trails": 275, "pass_type": "Epic", "resort_website": "https://www.vail.com/"},
{"address": "210 Beaver Creek Plaza", "city": "Beaver Creek", "state": "CO", "zipcode": 81620, "name": "Beaver Creek Resort", "photo_url": "https://i0.wp.com/images.303magazine.com/uploads/2022/09/iStock-502757710.jpg?ssl=1", "average_rating": 0, "elevation": 11440, "price": 5, "vertical_drop": 3340, "num_trails": 163, "pass_type": "Epic", "resort_website": "https://www.beavercreek.com/"},
{"address": "11 Snowmass Rd", "city": "Crested Butte", "state": "CO", "zipcode": 81224, "name": "Crested Butte Ski Resort", "photo_url": "https://dam-assets.vailresorts.com/is/image/vailresorts/02-5?resMode=sharp2&wid=412&fit=constrain,1&dpr=on,2.625", "average_rating": 0, "elevation": 12162, "price": 2, "vertical_drop": 2787, "num_trails": 165, "pass_type": "Epic", "resort_website": "https://www.skicb.com/"},
{"address": "565 Mountain Village Blvd", "city": "Telluride", "state": "CO", "zipcode": 81435, "name": "Telluride Ski Resort", "photo_url": "https://www.powderhounds.com/site/DefaultSite/filesystem/images/USA/Telluride/Overview/01.jpg", "average_rating": 0, "elevation": 13320, "price": 3, "vertical_drop": 4425, "num_trails": 149, "pass_type": "Epic", "resort_website": "https://tellurideskiresort.com/"},
{"address": "209 Ten Mile Circle", "city": "Copper Mountain", "state": "CO", "zipcode": 80443, "name": "Copper Mountain Resort", "photo_url": "https://www.skimag.com/wp-content/uploads/2022/10/Copper-665-CM_Winter_USASA-Boarder-and-Ski-Cross_2-13-22_CD_01-1.jpg", "average_rating": 0, "elevation": 12441, "price": 3, "vertical_drop": 2738, "num_trails": 150, "pass_type": "Ikon", "resort_website": "https://www.coppercolorado.com/"},
{"address": "2861 Eldora Ski Rd", "city": "Nederland", "state": "CO", "zipcode": 80466, "name": "Eldora Mountain Resort", "photo_url": "http://www.coloradoski.com/wp-content/uploads/2022/09/DroneOverviewFromAboveSundance_CullenMcHale-scaled.jpg", "average_rating": 0, "elevation": 10800, "price": 1, "vertical_drop": 1600, "num_trails": 61, "pass_type": "Ikon", "resort_website": "https://www.eldora.com/"},
{"address": "2305 Mt Werner Cir", "city": "Steamboat Springs", "state": "CO", "zipcode": 80487, "name": "Steamboat Ski Resort", "photo_url": "https://lh3.googleusercontent.com/p/AF1QipPwcKaUfHv5aYweipBpWtaykVhojIvn13F5_nN-=s680-w680-h510", "average_rating": 0, "elevation": 10568, "price": 5, "vertical_drop": 3668, "num_trails": 171, "pass_type": "Ikon", "resort_website": "https://www.steamboat.com/"},
{"address": "85 Parsenn Rd", "city": "Winter Park", "state": "CO", "zipcode": 80482, "name": "Winter Park Ski Resort", "photo_url": "https://www.mtnfeed.com/images/resorts/winter-park/vasquez-ridge-territory-lrg.jpg", "average_rating": 0, "elevation": 12060, "price": 4, "vertical_drop": 3060, "num_trails": 171, "pass_type": "Ikon", "resort_website": "https://www.winterparkresort.com/"},
{"address": "28194 US-6", "city": "Dillon", "state": "CO", "zipcode": 80435, "name": "Arapahoe Basin", "photo_url": "https://www.skimag.com/wp-content/uploads/2022/10/ABasin-100-ZACH-RYAN-skiing-frontside-terrani-off-Pali-Lift-2.jpg", "average_rating": 0, "elevation": 13050, "price": 4, "vertical_drop": 2530, "num_trails": 147, "pass_type": "Ikon", "resort_website": "https://www.arapahoebasin.com/"},
{"address": "601 E Dean St", "city": "Aspen", "state": "CO", "zipcode": 81611, "name": "Aspen Mountain", "photo_url": "http://www.coloradoski.com/wp-content/uploads/2022/09/22-23_ASC_Scenic_018-scaled.jpg", "average_rating": 0, "elevation": 11212, "price": 4, "vertical_drop": 3267, "num_trails": 76, "pass_type": "Ikon", "resort_website": "https://www.aspensnowmass.com/four-mountains/aspen-mountain"},
{"address": "75 Boomerang Rd", "city": "Aspen", "state": "CO", "zipcode": 81611, "name": "Aspen Highlands", "photo_url": "https://images.theoutbound.com/uploads/1454957078216/phjmqv8hymi/8c5192f46352088d82411a0c8d40b429?w=1200&h=630&fit=crop&dpr=1&q=60&s=381336cbf7279215013b6ebf8f7888fa", "average_rating": 0, "elevation": 11675, "price": 4, "vertical_drop": 3635, "num_trails": 117, "pass_type": "Ikon", "resort_website": "https://www.aspensnowmass.com/four-mountains/aspen-highlands"},
{"address": "38700 CO-82", "city": "Aspen", "state": "CO", "zipcode": 81611, "name": "Aspen Buttermilk", "photo_url": "https://www.aspensnowmass.com/-/media/aspen-snowmass/images/hero/hero-image/winter/2021-22/buttermilk-hero-08182021.jpg?mw=1506&mh=930&hash=229D36BB88CF0CB6B84671F475590F31", "average_rating": 0, "elevation": 9900, "price": 4, "vertical_drop": 2030, "num_trails": 44, "pass_type": "Ikon", "resort_website": "https://www.aspensnowmass.com/four-mountains/buttermilk"},
{"address": "", "city": "Snowmass Village", "state": "CO", "zipcode": 81611, "name": "Aspen Snowmass", "photo_url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.aspensnowmass.com%2Ffour-mountains%2Fsnowmass&psig=AOvVaw2f4Zi_YHS1oWqfU0LkRUjH&ust=1680041044334000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCPDgg9-O_f0CFQAAAAAdAAAAABAE", "average_rating": 0, "elevation": 12510, "price": 4, "vertical_drop": 4030, "num_trails": 91, "pass_type": "Ikon", "resort_website": "https://www.aspensnowmass.com/four-mountains/snowmass?utm_source=google&utm_medium=organic&utm_campaign=gmb_profile"}]


# 4/4/23: working on Redux install:
#     >docker exec module3-project-gamma-ghi-1 npm install @reduxjs/toolkit react-redux
